export type Lab = {
  slug: string;
  version: string;
  title: string;
  summary: string;
  track: "web" | "api" | "tz-local";
  owasp: string[];
  cwe: number[];
  difficulty: "beginner" | "intermediate" | "advanced";
  timeMinutes: number;
  objectives: { id: string; title: string }[];
  i18n?: { en: boolean; sw: boolean };
  origin?: "native" | "third-party";
};

/* Mirrors labs/ manifests (static fallback; API-driven when live). */
export const LABS: Lab[] = [
  {
    slug: "web-http-01",
    version: "0.1.0",
    title: "HTTP in Depth: Methods, Override Headers, Status",
    summary: "Request/response anatomy, then abuse X-HTTP-Method-Override.",
    track: "web",
    owasp: ["A01:2021-Broken Access Control"],
    cwe: [650],
    difficulty: "beginner",
    timeMinutes: 30,
    objectives: [{ id: "override-note", title: "Change the note via GET + override" }],
  },
  {
    slug: "web-cookies-01",
    version: "0.1.0",
    title: "Cookies & Sessions: Don't Trust the Jar",
    summary: "Forge an unsigned session cookie, then fix with HMAC signing.",
    track: "web",
    owasp: ["A07:2021-Identification and Authentication Failures"],
    cwe: [565],
    difficulty: "beginner",
    timeMinutes: 45,
    objectives: [{ id: "become-admin", title: "Forge admin cookie, read /admin" }],
  },
  {
    slug: "web-headers-01",
    version: "0.1.0",
    title: "TLS Headers, CORS & CSP",
    summary: "Spot missing headers and wildcard CORS, then lock both down.",
    track: "web",
    owasp: ["A05:2021-Security Misconfiguration"],
    cwe: [942],
    difficulty: "beginner",
    timeMinutes: 30,
    objectives: [{ id: "cors-steal", title: "Cross-origin read with evil Origin" }],
  },
  {
    slug: "web-authz-01",
    version: "0.1.0",
    title: "Auth Boundaries: Function-Level Authorization",
    summary: "Self-promote via an unguarded function, then gate it.",
    track: "web",
    owasp: ["A01:2021-Broken Access Control"],
    cwe: [285],
    difficulty: "intermediate",
    timeMinutes: 45,
    objectives: [{ id: "escalate-role", title: "Promote user→admin, read flag" }],
  },
  {
    slug: "web-report-01",
    version: "0.1.0",
    title: "Evidence & Reporting: Write It Like a Pro",
    summary: "Turn observations into a complete, gradeable finding.",
    track: "web",
    owasp: ["A09:2021-Security Logging and Monitoring Failures"],
    cwe: [778],
    difficulty: "beginner",
    timeMinutes: 30,
    objectives: [{ id: "write-finding", title: "Submit a complete finding" }],
  },
  {
    slug: "web-sqli-01",
    version: "0.1.0",
    title: "Injection: SQL Login Bypass",
    summary: "Break string-concatenated login, then parameterize it.",
    track: "web",
    owasp: ["A03:2021-Injection"],
    cwe: [89],
    difficulty: "intermediate",
    timeMinutes: 45,
    objectives: [{ id: "sqli-login", title: "Log in as admin without password" }],
  },
  {
    slug: "web-xss-01",
    version: "0.1.0",
    title: "XSS: Stored Payload, Proved",
    summary: "Persist a script marker unescaped, prove reflection, then escape + CSP.",
    track: "web",
    owasp: ["A03:2021-Injection"],
    cwe: [79],
    difficulty: "intermediate",
    timeMinutes: 45,
    objectives: [{ id: "stored-xss", title: "Store script marker, claim flag" }],
  },
  {
    slug: "web-ssrf-01",
    version: "0.1.0",
    title: "SSRF: Fetch the Internal Secret",
    summary: "Pivot through an open fetcher to mock metadata, then allowlist.",
    track: "web",
    owasp: ["A10:2021-Server-Side Request Forgery"],
    cwe: [918],
    difficulty: "intermediate",
    timeMinutes: 45,
    objectives: [{ id: "fetch-secret", title: "Fetch internal secret via /fetch" }],
  },
  {
    slug: "api-bola-01",
    version: "0.1.0",
    title: "API BOLA: Yours, Mine, and the SSN Field",
    summary: "Cross-user invoice read plus property leak, then enforce both.",
    track: "api",
    owasp: ["API1:2023-BOLA"],
    cwe: [639],
    difficulty: "intermediate",
    timeMinutes: 45,
    objectives: [{ id: "bola-read", title: "Read bob's invoice as alice" }],
  },
  {
    slug: "api-mass-01",
    version: "0.1.0",
    title: "API Mass Assignment via PATCH",
    summary: "Sneak role=admin through profile update, then allowlist.",
    track: "api",
    owasp: ["API6:2023-Unrestricted Business Flows"],
    cwe: [915],
    difficulty: "intermediate",
    timeMinutes: 30,
    objectives: [{ id: "mass-assign", title: "PATCH role=admin, read flag" }],
  },
  {
    slug: "api-jwt-01",
    version: "0.1.0",
    title: "API JWT: The alg=none Trap",
    summary: "Forge unsigned admin token, then enforce verification.",
    track: "api",
    owasp: ["API2:2023-Broken Authentication"],
    cwe: [347],
    difficulty: "intermediate",
    timeMinutes: 45,
    objectives: [{ id: "jwt-none", title: "Mint unsigned admin JWT" }],
  },
  {
    slug: "api-ratelimit-01",
    version: "0.1.0",
    title: "API Abuse: Coupon Without Limits",
    summary: "Redeem one coupon forever, then cap the flow.",
    track: "api",
    owasp: ["API4:2023-Unrestricted Resource Consumption"],
    cwe: [770],
    difficulty: "beginner",
    timeMinutes: 30,
    objectives: [{ id: "abuse-redeem", title: "Redeem WELCOME10 five times" }],
  },
  {
    slug: "web-csrf-01",
    version: "0.1.0",
    title: "CSRF: The Transfer That Forged Itself",
    summary: "Cookie-authed transfer, then token binding.",
    track: "web",
    owasp: ["A01:2021-Broken Access Control"],
    cwe: [352],
    difficulty: "intermediate",
    timeMinutes: 45,
    objectives: [{ id: "csrf-transfer", title: "Transfer on victim session" }],
  },
  {
    slug: "web-traversal-01",
    version: "0.1.0",
    title: "Traversal: Walk Out of /files/",
    summary: "Escape the jail with ../, then allowlist.",
    track: "web",
    owasp: ["A01:2021-Broken Access Control"],
    cwe: [22],
    difficulty: "beginner",
    timeMinutes: 30,
    objectives: [{ id: "traverse-read", title: "Read secret.txt via traversal" }],
  },
  {
    slug: "web-upload-01",
    version: "0.1.0",
    title: "Uploads: The SVG That Ran",
    summary: "Scripted SVG served as image, then type gates.",
    track: "web",
    owasp: ["A03:2021-Injection"],
    cwe: [434],
    difficulty: "intermediate",
    timeMinutes: 45,
    objectives: [{ id: "upload-xss", title: "Serve live SVG marker" }],
  },
  {
    slug: "web-crypto-01",
    version: "0.1.0",
    title: "Crypto: The Reset Token You Can Mint",
    summary: "Forge predictable reset tokens, then sign them.",
    track: "web",
    owasp: ["A02:2021-Cryptographic Failures"],
    cwe: [330],
    difficulty: "intermediate",
    timeMinutes: 45,
    objectives: [{ id: "forge-reset", title: "Mint admin reset token" }],
  },
  {
    slug: "web-idor-01",
    version: "0.1.0",
    title: "Broken Access Control: IDOR",
    summary: "Log in as amina, read juma's order, enforce ownership.",
    track: "web",
    owasp: ["A01:2021-Broken Access Control"],
    cwe: [639],
    difficulty: "beginner",
    timeMinutes: 45,
    objectives: [{ id: "read-other-order", title: "Read juma's order as amina" }],
  },
  {
    slug: "mpesa-bola-01",
    version: "0.1.0",
    title: "M-Pesa Mock: BOLA + Callback Forgery",
    summary: "TZ-local API lab: account binding and callback HMAC on a mock mobile-money API.",
    track: "tz-local",
    owasp: ["API1:2023-BOLA", "API8:2023-Security Misconfiguration"],
    cwe: [639, 347],
    difficulty: "intermediate",
    timeMinutes: 60,
    objectives: [
      { id: "read-foreign-balance", title: "Read another account balance" },
      { id: "forge-callback", title: "Forge STK callback without valid HMAC" },
    ],
    i18n: { en: true, sw: true },
  },
  {
    slug: "curated-juice-shop",
    version: "0.1.0",
    title: "Curated: OWASP Juice Shop (Third-Party)",
    summary: "Full Top-Ten playground, wrapped. Evidence-graded by instructors.",
    track: "web",
    owasp: ["A01:2021-Broken Access Control"],
    cwe: [79],
    difficulty: "intermediate",
    timeMinutes: 120,
    objectives: [
      { id: "scoreboard-found", title: "Find the score board (evidence)" },
      { id: "admin-login", title: "Admin login challenge (evidence)" },
    ],
    origin: "third-party",
  },
];

export function getLab(slug: string): Lab | undefined {
  return LABS.find((l) => l.slug === slug);
}
